-- 페이지 설정 확장: 헤더 표시 여부, 여백(padding)
ALTER TABLE pages ADD COLUMN IF NOT EXISTS show_header BOOLEAN DEFAULT true;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS padding_top INTEGER DEFAULT 20;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS padding_right INTEGER DEFAULT 20;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS padding_bottom INTEGER DEFAULT 20;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS padding_left INTEGER DEFAULT 20;
